'''
    AUTO GENERATED BY TOOLS, DO NOT EDIT
    2018-10-14 16:32:15
'''

t_wx = {
    "cfg" : {
        '''
        key: 键
        value: 值
        desc: 描述

        '''
        "appid" : {
            "key" : "appid",
            "value" : "wx6ac3f5090a6b99c5",
            "desc" : "小游戏APPID",
        },
        "secret" : {
            "key" : "secret",
            "value" : "test",
            "desc" : "用于根据code获取openid的密钥",
        },
        "grant_type" : {
            "key" : "grant_type",
            "value" : "1",
            "desc" : "授权码",
        },

    },

}